name: Build and deploy Node.js app to Azure Web App - petzClinic

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Build backend
        run: |
          cd server
          npm install
          npm run start  # Assuming you have a build script. If not, just 'npm install' is fine.

      - name: Build frontend
        run: |
          cd client
          npm install
          npm run dev  # This should be a production build command

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1A70DC0A642342D782856784B7A868F5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_53C16070B0614F3DB0FA763E17364525 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_864D28424B3F4C5DBCF1B038B4956630 }}

      - name: Set Azure App Service settings
        uses: azure/appservice-settings@v1
        with:
          app-name: 'petzClinic'
          slot-name: 'Production'
          app-settings-json: >
            [
              {"name": "MONGO_URI", "value": "${{ secrets.MONGO_URI }}", "slotSetting": false},
              {"name": "SECRET", "value": "${{ secrets.SECRET }}", "slotSetting": false}
            ]

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'petzClinic'
          slot-name: 'Production'
          package: .
